[package]
name = "ernisto/wrapper"
version = "0.4.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Collector = "ernisto/collector@0.1.2"
Signal = "ernisto/signal@0.1.1"